server:
  port: 5009

spring:
  application:
    name: booking-service

  datasource:
    url: jdbc:mysql://localhost:3306/airline_booking_db
    username: root
    password: Pradeep@drait123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: booking-service-group

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
